### Criar um deck
POST http://localhost:8080/decks
Content-Type: application/json

{
  "name": "Deck de teste aaaaaaaaaa aaaaaa robson",
  "description": "Deck de commander do robson",
  "format": "COMMANDER"
}

###

### Buscar todos os decks
GET http://localhost:8080/decks

###

### Buscar um deck por ID
GET http://localhost:8080/decks/4

### Atualizar um deck
PUT http://localhost:8080/decks/4
Content-Type: application/json

{
  "description": "um deck qualquer"
}

### Deletar um deck
DELETE http://localhost:8080/decks/3

### Adicionar uma carta ao deck
POST http://localhost:8080/decks/4/cards
Content-Type: application/json

{
  "id": 40
}

### Remover uma carta do deck
DELETE http://localhost:8080/decks/2/cards/40