### Criar um deck
POST http://localhost:4052/decks
Content-Type: application/json

{
  "name": "Deck do Robson de commander",
  "description": "Deck poderoso com cartas lendárias",
  "format": "COMMANDER"
}

###

### Buscar todos os decks
GET http://localhost:4052/decks

###

### Buscar um deck por ID
GET http://localhost:4052/decks/2

### Atualizar um deck
PUT http://localhost:4052/decks/4
Content-Type: application/json

{
  "format": "Commander"
}

### Deletar um deck
DELETE http://localhost:4052/decks/3

### Adicionar uma carta ao deck
POST http://localhost:4052/decks/2/cards
Content-Type: application/json

{
  "id": 1
}

### Remover uma carta do deck
DELETE http://localhost:4052/decks/2/cards/1