name: CI - Robson Deck (Docker)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: pryor
          POSTGRES_PASSWORD: robson
          POSTGRES_DB: robsonDeck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://pryor:robson@localhost:5432/robsonDeck
      NODE_ENV: test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Aplicar migrações
        run: npx prisma migrate deploy

      - name: Rodar testes com cobertura
        run: npm run coverage
